/**
 * Copyright (C) 2026. Bao Han <erbws@qq.com>
 */

package ohos_app_cangjie_mpvcj.models

public class AudioParams {
    /// The sample format as string. This uses the same names as used in other places of mpv.
    public var format = ""
    
    /// Sample rate.
    public var samplerate = 0
    
    /// The channel layout as a string. This is similar to what the --audio-channels accepts.
    public var channels = ""
}
